<?php
function cipher_menu() {
  $items['cipher_encrypt'] = array(
    'title' => 'Cipher Encryption',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('cipher_form'),
    'access callback' => TRUE,
    'type' => MENU_NORMAL_ITEM,
  );
  $items['cipher_success'] = array(
    'title' => 'Success',
    'page callback' => 'cipher_success',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );

  return $items;
}

function cipher_form() {
  $form['phrase'] = array (
    '#title' => 'Phrase',
    '#type' => 'textfield',
    '#description' => t('Please enter a phrase to be encrypted.'),
    "#required" => TRUE,
  );
  $form['shift_value'] = array (
    '#title' => 'Shift Value',
    '#type' => 'textfield',
    '#description' => t('Please enter a number of spaces to shift (maximum of 25 spaces).'),
    '#element_validate' => array('element_validate_integer_positive', 'element_validate_range'),
    "#required" => TRUE,
  );
  $form['direction'] = array (
    '#title' => 'Direction',
    '#type' => 'textfield',
    '#description' => t('Please enter a direction to shift letters (left or right).'),
    '#element_validate' => array( 'element_validate_direction'),
    "#required" => TRUE,
  );

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => 'Encrypt!',
  );

  return $form;
}

function element_validate_range($element) {
  if($element['#value'] < 1 || $element['#value'] > 25){
    form_error($element, t('Please enter a number between 1 and 25.'));
  }
}

function element_validate_direction($element) {
  $direction = drupal_strtolower($element['#value']);
  $allowed = array('left','right');
  if(!in_array($direction, $allowed)){
    form_error($element, t('Please enter left or right.'));
  }
}

function cipher_form_submit($form, &$form_state) {
  $phrase = drupal_strtolower($form_state['values']['phrase']);
  $shift_value = $form_state['values']['shift_value'];
  $direction = $form_state['values']['direction'];
  $encrypted_phrase = null;

  $phrase_arr = str_split($phrase);
// for each letter of the string
foreach($phrase_arr as $letter) {
  // check for alphabetical letter
  if(ctype_alnum($letter)) {
    // convert to ASCII Dec ** lowercase alphabet starts at 97 ***
    $ascii = ord($letter) - 97;

    if($direction === "right"){
      $num_letter = $ascii + 97 + $shift_value;
      if($num_letter > 122){
        $num = $num_letter - 26;
        $encrypted_phrase .= chr($num);
      } else {
        $encrypted_phrase .= chr($num_letter);
      }
      // shift to the left
    }else {
      $encrypted_phrase .= chr($ascii + 123 - $shift_value);
    }
  } else {
    $encrypted_phrase .= $letter;
  }
}

  $_SESSION['phrase_output'] = $encrypted_phrase;
  $form_state['redirect'] = 'cipher_success';
}

function cipher_success() {
  $encrypted_phrase = $_SESSION['phrase_output'];
  return 'You have successfully encrypted your phrase! Here is your super secret phrase: <strong>' . $encrypted_phrase . '</strong>';

}
